name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  check:
    strategy:
      fail-fast: false
      matrix:
        check:
          - format
          - type
    name: Check ${{ matrix.check }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up env
        uses: the-guild-org/shared-config/setup@v1
        with:
          node-version-file: .node-version
      - name: Install
        run: yarn install
      - name: Check
        run: yarn check:${{ matrix.check }}

  build: # making sure build works so it doesn't fail on us during release
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up env
        uses: the-guild-org/shared-config/setup@v1
        with:
          node-version-file: .node-version
      - name: Install
        run: yarn install
      - name: Build
        run: yarn build
