name: Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  unit:
    strategy:
      fail-fast: false
      matrix:
        node-version:
          - 18
          - 20
          - 22
    name: Unit / Node v${{matrix.node-version}}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up env
        uses: the-guild-org/shared-config/setup@v1
        with:
          node-version: ${{matrix.node-version}}
      - name: Install
        run: yarn install
      - name: Test
        run: yarn test

  # TODO: various gateway runners
  e2e:
    needs: [unit]
    strategy:
      fail-fast: false
      matrix:
        node-version:
          - 18
          - 20
          - 22
    name: E2E / Node v${{matrix.node-version}}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up env
        uses: the-guild-org/shared-config/setup@v1
        with:
          node-version: ${{matrix.node-version}}
      - name: Install
        run: yarn install
      - name: Test
        run: yarn test:e2e
