name: Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  unit:
    strategy:
      fail-fast: false
      matrix:
        node-version:
          - 18
          - 20
          - 22
    name: Unit / Node v${{matrix.node-version}}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up env
        uses: the-guild-org/shared-config/setup@v1
        with:
          node-version: ${{matrix.node-version}}
      - name: Install
        run: yarn install
      - name: Test
        run: yarn test

  # TODO: various gateway runners
  e2e:
    strategy:
      fail-fast: false
      matrix:
        node-version:
          - 18
          - 20
          - 22
    name: E2E / Node v${{matrix.node-version}}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up env
        uses: the-guild-org/shared-config/setup@v1
        with:
          node-version: ${{matrix.node-version}}
      - name: Install
        run: yarn install
      - name: Hash Docker Images
        if: runner.os == 'Linux'
        id: hash-docker-images
        run: | # get all "image: '" occurrences in the e2e tests and hash them
          echo "result=$(grep -r -h "image: '" e2e | shasum | base64)" >> "$GITHUB_OUTPUT"
      - name: Cache Docker Images
        if: runner.os == 'Linux'
        uses: ScribeMD/docker-cache@0.5.0
        continue-on-error: true
        with:
          key: docker-images-${{ runner.os }}-${{ steps.hash-docker-images.outputs.result }}
      - name: Test
        run: yarn e2e:test
